services:
  semaphore_db:
    image: postgres
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semaphore
    volumes:
      - semaphore_postgres:/var/lib/postgresql/data
    networks:
      - semaphore_network
  semaphore:
    ports:
      - 3000:3000
    depends_on:
      - semaphore_db
    image: semaphoreui/semaphore:v2.16.41
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: semaphore_db
      SEMAPHORE_DB_NAME: semaphore
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: postgres
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@bnbdevelopment.hu
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
    networks:
      - semaphore_network
volumes:
  semaphore_data:
  semaphore_config:
  semaphore_postgres:
networks:
  semaphore_network: {driver: "bridge"}