---
name: Build and push HANDLE SERVER to GCP
on: workflow_dispatch
jobs:
  build-push-gcr:
    name: Checkout
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: IMAGE
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Change Chart values
      run: |
        cd test
        sed 's/handle_tag: .*/handle_tag: '${{ github.run_number }}'/' test.yaml > temp.yaml && mv temp.yaml test.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add test.yaml
        git commit -m "Change release tag in test.yaml"
        git push